#!/bin/bash

wid=$1
class=$2
instance=$3
consequences=$4

# notify-send "wid: $wid"
# notify-send "class: $class"
# notify-send "instance: $instance"
# notify-send "consequences: $consequences"

main() {
    case "$class" in
        Spotify)
            echo "desktop=1 follow=off"
            ;;
        "")
            sleep 0.5

            wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))

            class=${wm_class[-1]}

            [[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}

            [[ -n $class ]] && main
            ;;
    esac
}

main
