#! /bin/sh

export WALLPAPER="$HOME/.config/bspwm/wallpapers/space-orange.jpg"

# Monitors
export MONITOR_LEFT="DisplayPort-5"
export MONITOR_TOP="DisplayPort-4"
export MONITOR_RIGHT="DisplaPort-3"



# Kill previous processes
killall sxhkd
killall dunst
killall polybar
killall wal
killall picom
killall redshift

sxhkd &
dunst &
wal -i "$WALLPAPER"
picom &
redshift &
xset s off -dpms &
xsetroot -cursor_name left_ptr &

bspc config top_padding 	0

# Note: hostname command requires 'inetutils' package
if [[ $(hostname) == 'arch' ]]; then
	# Left
	bspc monitor $MONITOR_LEFT -d 1 2 3
	# Right
	bspc monitor $MONITOR_RIGHT -d 1 2 3
	# Top
	bspc monitor $MONITOR_TOP -d 1 2 3

	# Polybar spacing
	bspc config -m $MONITOR_LEFT top_padding	38
	export MONITOR=$MONITOR_LEFT
fi

polybar windowtitle &
polybar info &

bspc config border_width        0
bspc config window_gap		8

bspc config right_padding 	0
bspc config bottom_padding 	0
bspc config left_padding 	0

bspc config split_ratio       	0.50
bspc config borderless_monocle 	true
bspc config gapless_monocle    	true

exec --no-startup-id ~/.screenlayout/desktop.sh
