#! /bin/sh

export WALLPAPER="$HOME/.config/bspwm/wallpapers/cyberpunk-1.jpg"

# Monitors

# Qt Kvantum theme
export QT_STYLE_OVERRIDE=kvantum

# Kill previous processes
killall sxhkd
killall dunst
killall polybar
killall wal
killall picom
killall redshift
killall nm-applet

sxhkd &
dunst &
wal -i "$WALLPAPER"
wal-polybar
picom &
redshift &
nm-applet &

xset s off -dpms &
xsetroot -cursor_name left_ptr &
xrdb $HOME/.Xresources & 

bspc config top_padding 	0

export MONITOR='eDP1'

# Note: hostname command requires 'inetutils' package
if [[ $(hostname) == 'archtop' ]]; then
	bspc monitor $MONITOR -d 1 2 3 4 5 6 7 8 9
	
	bspc config -m $MONITOR top_padding 25
fi

polybar --reload simple &

bspc config border_width        1
bspc config window_gap		8

bspc config right_padding 	0
bspc config bottom_padding 	0
bspc config left_padding 	0

bspc config split_ratio       	0.50
bspc config borderless_monocle 	false
bspc config gapless_monocle    	true
bspc config single_monocle      true

bspc config focused_border_color "#913852"
bspc config active_border_color "#000000"
bspc config normal_border_color "#000000"

bspc rule -a Emacs state=tiled
