#! /bin/sh

export WALLPAPER="$HOME/.config/bspwm/wallpapers/space-orange.jpg"

# Kill previous processes
killall sxhkd
killall dunst
killall polybar
killall wal
killall picmon
killall redshift

sxhkd &
dunst &
wal -i $WALLPAPER &
picom &
redshift &
xset s off -dpms &
xsetroot -cursor_name left_ptr &

bspc config top_padding 	0

if [[ $(hostname) == 'arch' ]]; then
	# Left
	bspc monitor DisplayPort-2 -d 1 2 3
	# Right
	bspc monitor DisplayPort-0 -d 1 2 3
	# Top
	bspc monitor DisplayPort-1 -d 1 2 3

	# Polybar spacing
	bspc config -m DisplayPort-2 top_padding	38
	export MONITOR="DisplayPort-2"
fi

polybar windowtitle &
polybar info &

bspc config border_width        0
bspc config window_gap		8

bspc config right_padding 	0
bspc config bottom_padding 	0
bspc config left_padding 	0

bspc config split_ratio       	0.50
bspc config borderless_monocle 	true
bspc config gapless_monocle    	true

exec --no-startup-id ~/.screenlayout/desktop.sh
